version: '3'

services:
  golang:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    command: sleep 99999
    volumes:
      - ./:/app
    networks:
      - internal
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - ./data/zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - internal
    restart: always
  #
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - ./data/kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CLIENT_USER=bambo_user
      - KAFKA_CLIENT_PASSWORD=SoftelTeam321!
    depends_on:
      - zookeeper
    networks:
      - internal

networks:
  internal:
    driver: bridge
  public:
    driver: bridge